package controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.TableView;
import javafx.stage.Stage;
import javafx.scene.control.TableColumn;

public class SemesterViewController {
	@FXML
	private Button btnNeu;
	@FXML
	private Button btnBearbeiten;
	@FXML
	private Button btnLoeschen;
	@FXML
	private Button btnZurueck;
	@FXML
	private TableView tblView;
	@FXML
	private TableColumn colSemester;
	@FXML
	private TableColumn colWertung;
	@FXML
	private TableColumn colSchnitt;

	// Event Listener on Button[#btnNeu].onAction
	@FXML
	public void btnNeuClicked(ActionEvent event) {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/view/SemesterEditView.fxml"));
			Parent rootComponent = loader.load();
			Stage stage = new Stage();
			Scene scene = new Scene(rootComponent);
			//scene.getStylesheets().add(getClass().getResource("/application/DarkTheme.css").toExternalForm());
			stage.setScene(scene);
			stage.show();
		} catch(Exception e) {
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#btnBearbeiten].onAction
	@FXML
	public void btnBearbeitenClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnLoeschen].onAction
	@FXML
	public void btnLoeschenClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnZurueck].onAction
	@FXML
	public void btnZurueckClicked(ActionEvent event) {
		// TODO Autogenerated
	}
}
