package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.stage.Window;
import javafx.event.ActionEvent;

public class SemesterEditViewController {
	@FXML
	private Button btnSpeichern;
	@FXML
	private Button btnAbbrechen;
	@FXML
	private TextField txtSemester;
	@FXML
	private TextField txtWertung;

	// Event Listener on Button[#btnSpeichern].onAction
	@FXML
	public void btnSpeichernClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAbbrechen].onAction
	@FXML
	public void btnAbbrechenClicked(ActionEvent event) {
		Window window = txtWertung.getScene().getWindow();
		((Stage)window).close();
	}
}
